name: reference_parser
description: >-
  A package that allows you to parse strings for bible references or 
  match them to their bible verses.
  Can parse varying formats of references and multiple references at a time.
version: 3.0.0
homepage: https://github.com/joshpetit/reference_parser
issue_tracker:  https://github.com/joshpetit/reference_parser/issues
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  html: ^0.15.0
  http: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
